export const scopes = [
  "user-read-private",
  "playlist-read-private",
  "playlist-read-collaborative",
  "playlist-modify-private",
  "user-read-recently-played",
  "playlist-modify-private",
  "ugc-image-upload",
  "user-follow-modify",
  "user-follow-read",
  "user-library-read",
  "user-library-modify",
  "user-top-read",
  "user-read-email",
  "user-read-playback-state",
];
